name: Testing

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  rack-protection:
    name: rack-protection (${{ matrix.ruby }}, rack ${{ matrix.rack }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        rack:
          - stable
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "jruby"
          - "truffleruby"
        include:
          # Rack
          - { ruby: 3.2, rack: head }
          # Never fail our build due to problems with head
          - { ruby: ruby-head, rack: stable, allow-failure: true }
    env:
      rack: ${{ matrix.rack }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: setup-ruby
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
        working-directory: rack-protection
    - name: Run rack-protection tests
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: protection-tests
      working-directory: rack-protection
      run: |
        bundle exec rake
    # because continue-on-error marks the steps as pass even if they fail
    - name: "setup-ruby (bundle install) outcome: ${{ steps.setup-ruby.outcome }}"
      run: ""
    - name: "rack-protection tests outcome: ${{ steps.protection-tests.outcome }}"
      run: ""
    - uses: zzak/action-discord@v6
      if: failure() && github.ref_name == 'main'
      continue-on-error: true # always allow failure
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
  sinatra:
    name: ${{ matrix.ruby }} (Rack ${{ matrix.rack }}, Rack::Session ${{ matrix.rack_session }}, Puma ${{ matrix.puma }}, Tilt ${{ matrix.tilt }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        puma:
          - stable
        rack:
          - stable
        rack_session:
          - stable
        tilt:
          - stable
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "jruby"
        include:
          # Rack
          - { ruby: 3.2, rack: head,   puma: stable,   tilt: stable, rack_session: stable, allow-failure: true }
          # Rack::Session
          - { ruby: 3.2, rack: stable, puma: stable,   tilt: stable, rack_session: head,   allow-failure: true }
          # Puma
          - { ruby: 3.2, rack: stable, puma: head,     tilt: stable, rack_session: stable, allow-failure: true }
          # Tilt
          - { ruby: 3.2, rack: stable, puma: stable,   tilt: head,   rack_session: stable, allow-failure: true }
          # Never fail our build due to problems with head
          - { ruby: ruby-head,        rack: stable, puma: stable, tilt: stable, rack_session: stable, allow-failure: true }
          - { ruby: jruby-head,       rack: stable, puma: stable, tilt: stable, rack_session: stable, allow-failure: true }
          - { ruby: truffleruby-head, rack: stable, puma: stable, tilt: stable, rack_session: stable, allow-failure: true }
          # truffleruby 24 fails, see https://github.com/sinatra/sinatra/issues/2007
          - { ruby: truffleruby,      rack: stable, puma: stable, tilt: stable, rack_session: stable, allow-failure: true }

    env:
      rack: ${{ matrix.rack }}
      rack_session: ${{ matrix.rack_session }}
      puma: ${{ matrix.puma }}
      tilt: ${{ matrix.tilt }}

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes \
          pandoc \
          nodejs \
          pkg-config \
          libxml2-dev \
          libxslt-dev \
          libyaml-dev

    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: setup-ruby
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        # Update rubygems due to https://github.com/rubygems/rubygems/pull/6490
        rubygems: ${{ matrix.ruby == '3.0' && 'latest' || 'default' }}

    - name: Run sinatra tests
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: tests
      run: bundle exec rake

    - name: Run sinatra-contrib tests
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: contrib-tests
      working-directory: sinatra-contrib
      run: |
        bundle install --jobs=3 --retry=3
        bundle exec rake

    # because continue-on-error marks the steps as pass even if they fail
    - name: "setup-ruby (bundle install) outcome: ${{ steps.setup-ruby.outcome }}"
      run: ""
    - name: "sinatra tests outcome: ${{ steps.tests.outcome }}"
      run: ""
    - name: "sinatra-contrib tests outcome: ${{ steps.contrib-tests.outcome }}"
      run: ""

    - uses: zzak/action-discord@v6
      if: failure() && github.ref_name == 'main'
      continue-on-error: true # always allow failure
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
